---
netname: meshvpn
# we assume servers have online one interface
physical_ip: "{{ ansible_eth1.ipv4.address }}"

vpn_interface: tun0

vpn_netmask: 255.255.255.0
vpn_subnet_cidr_netmask: 32

# scw-metadata
scw_private_domain: priv.cloud.scaleway.com

api_floating_ip: 192.168.66.253
